### PR TITLE
Update name format and position

### PR DESCRIPTION
**Pull request by huijing**

### CODE REVIEW

**Comment by pepelsbey** [comment]
Oh, hello :) Thank you!

**Comment by pepelsbey** [comment]
It seems I rushed to merge it :(

In this dictionary we sort people by surname, that’s why we put surname first and then, after comma, goes name. I guess that’s was the case before your PR, right?

**Comment by MeFoDy** [comment]
@huijing, hello!
Let me clarify the order of the names. We have the next positioning: `Surname, Name`. As you explained, your surname is Chen and the first name is Hui Jing. So it looks like I created confusion with my message to you :) We had a correct order, but it needs to be approved by you to avoid one more confusion :)

**Comment by huijing** [comment]
Opps, in that case, should I change it back? I'll change it back with another pull request :p

**Pull request merged**
